"""Initial TradzLog schema.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-10-08

Explicit baseline generated with `alembic revision --autogenerate` against an empty database. It
replaces the earlier version of this revision that called `Base.metadata.create_all`, and produces
the same schema (checked with pg_dump), so databases already at this revision need no change.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0001_initial_schema'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('asset_class', sa.Enum('STOCK', 'FUTURES', 'FOREX', 'OPTIONS', 'CRYPTO', 'COMMODITY', name='assetclass'), nullable=False),
    sa.Column('exchange', sa.String(length=80), nullable=True),
    sa.Column('tick_size', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('contract_size', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('point_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'asset_class', name='uq_instruments_symbol_asset_class')
    )
    op.create_index(op.f('ix_instruments_asset_class'), 'instruments', ['asset_class'], unique=False)
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan', sa.Enum('FREE', 'PRO', 'ELITE', name='plan'), nullable=False),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('broker', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('account_type', sa.Enum('LIVE', 'PAPER', 'PROP_FIRM', name='accounttype'), nullable=False),
    sa.Column('prop_firm_name', sa.String(length=120), nullable=True),
    sa.Column('max_daily_loss', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('max_total_loss', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('daily_profit_target', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('auth_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.Enum('EMAIL_VERIFICATION', 'PASSWORD_RESET', 'MAGIC_LINK', name='authtokenpurpose'), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_auth_tokens_token_hash', 'auth_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_auth_tokens_user_id'), 'auth_tokens', ['user_id'], unique=False)
    op.create_index('ix_auth_tokens_user_purpose', 'auth_tokens', ['user_id', 'purpose'], unique=False)
    op.create_table('billing_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'PRO', 'ELITE', name='plan'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'TRIALING', 'PAST_DUE', 'CANCELED', name='billingstatus'), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_customer_id', sa.String(length=120), nullable=True),
    sa.Column('provider_subscription_id', sa.String(length=120), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_subscriptions_provider_customer_id'), 'billing_subscriptions', ['provider_customer_id'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_provider_subscription_id'), 'billing_subscriptions', ['provider_subscription_id'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_user_id'), 'billing_subscriptions', ['user_id'], unique=False)
    op.create_index('ix_billing_subscriptions_user_status', 'billing_subscriptions', ['user_id', 'status'], unique=False)
    op.create_table('leaderboard_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('metric', sa.Enum('PROFIT_FACTOR', 'EXPECTANCY', 'WIN_RATE', name='leaderboardmetric'), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('asset_class_filter', sa.Enum('STOCK', 'FUTURES', 'FOREX', 'OPTIONS', 'CRYPTO', 'COMMODITY', name='assetclass'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_leaderboard_profiles_user')
    )
    op.create_index(op.f('ix_leaderboard_profiles_user_id'), 'leaderboard_profiles', ['user_id'], unique=False)
    op.create_table('mentor_access',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_user_id', sa.String(length=36), nullable=False),
    sa.Column('mentor_email', sa.String(length=255), nullable=False),
    sa.Column('mentor_name', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REVOKED', name='mentoraccessstatus'), nullable=False),
    sa.Column('can_view_journals', sa.Boolean(), nullable=False),
    sa.Column('can_comment', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_access_mentor_email'), 'mentor_access', ['mentor_email'], unique=False)
    op.create_index('ix_mentor_access_student', 'mentor_access', ['student_user_id', 'status'], unique=False)
    op.create_index(op.f('ix_mentor_access_student_user_id'), 'mentor_access', ['student_user_id'], unique=False)
    op.create_table('account_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('drawdown_from_peak', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('drawdown_pct', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date', name='uq_account_snapshots_account_date')
    )
    op.create_index(op.f('ix_account_snapshots_account_id'), 'account_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_snapshots_date'), 'account_snapshots', ['date'], unique=False)
    op.create_table('ai_insights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('PATTERN', 'COACHING', 'WEEKLY_SUMMARY', 'SETUP_ANALYSIS', name='aiinsighttype'), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('supporting_trade_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insights_account_id'), 'ai_insights', ['account_id'], unique=False)
    op.create_index(op.f('ix_ai_insights_user_id'), 'ai_insights', ['user_id'], unique=False)
    op.create_table('billing_invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=True),
    sa.Column('provider_invoice_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'PAID', 'VOID', 'UNCOLLECTIBLE', name='invoicestatus'), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('hosted_invoice_url', sa.String(length=1000), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['billing_subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_invoices_provider_invoice_id'), 'billing_invoices', ['provider_invoice_id'], unique=False)
    op.create_index(op.f('ix_billing_invoices_subscription_id'), 'billing_invoices', ['subscription_id'], unique=False)
    op.create_index('ix_billing_invoices_user_created', 'billing_invoices', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_billing_invoices_user_id'), 'billing_invoices', ['user_id'], unique=False)
    op.create_table('broker_syncs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('broker', sa.String(length=120), nullable=False),
    sa.Column('sync_type', sa.Enum('CSV', 'API', name='brokersynctype'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='brokersyncstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_syncs_account_id'), 'broker_syncs', ['account_id'], unique=False)
    op.create_table('daily_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('trades_count', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('breakeven', sa.Integer(), nullable=False),
    sa.Column('gross_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('commissions', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('avg_win', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('avg_loss', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('biggest_win', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('biggest_loss', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('r_multiple_sum', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date', name='uq_daily_stats_account_date')
    )
    op.create_index(op.f('ix_daily_stats_account_id'), 'daily_stats', ['account_id'], unique=False)
    op.create_index(op.f('ix_daily_stats_date'), 'daily_stats', ['date'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('instrument_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='direction'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='tradestatus'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('setup_tag', sa.String(length=80), nullable=True),
    sa.Column('timeframe', sa.String(length=16), nullable=True),
    sa.Column('planned_entry', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('planned_stop', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('planned_target', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('planned_rr', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('commissions', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('emotional_rating', sa.Integer(), nullable=True),
    sa.Column('mistake_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('journal_entry_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_account_id'), 'trades', ['account_id'], unique=False)
    op.create_index('ix_trades_account_opened', 'trades', ['account_id', 'opened_at'], unique=False)
    op.create_index(op.f('ix_trades_instrument_id'), 'trades', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_trades_setup_tag'), 'trades', ['setup_tag'], unique=False)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    op.create_index('ix_trades_user_status_opened', 'trades', ['user_id', 'status', 'opened_at'], unique=False)
    op.create_table('trading_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('MAX_DAILY_LOSS', 'MAX_DAILY_TRADES', 'MAX_POSITION_SIZE', 'MAX_CONSECUTIVE_LOSSES', 'MANDATORY_JOURNAL', 'MIN_RR', 'DAILY_PROFIT_TARGET', name='ruletype'), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('action', sa.Enum('WARN', 'LOCK_TRADING', 'NOTIFY', name='ruleaction'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_rules_account_id'), 'trading_rules', ['account_id'], unique=False)
    op.create_index(op.f('ix_trading_rules_user_id'), 'trading_rules', ['user_id'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trade_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('ENTRY', 'EXIT', 'ADD', 'PARTIAL_EXIT', name='executiontype'), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fees', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('broker_id', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_broker_id'), 'executions', ['broker_id'], unique=False)
    op.create_index(op.f('ix_executions_trade_id'), 'executions', ['trade_id'], unique=False)
    op.create_index('ix_executions_trade_time', 'executions', ['trade_id', 'executed_at'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('TRADE_REVIEW', 'DAILY', 'WEEKLY', 'FREEFORM', name='journaltype'), nullable=False),
    sa.Column('trade_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('market_condition', sa.Enum('TRENDING', 'RANGING', 'CHOPPY', 'HIGH_VOL', 'LOW_VOL', name='marketcondition'), nullable=True),
    sa.Column('key_lessons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_trade_id'), 'journal_entries', ['trade_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.create_index('ix_journal_user_date', 'journal_entries', ['user_id', 'date'], unique=False)
    op.create_table('public_trade_shares',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('trade_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('anonymized', sa.Boolean(), nullable=False),
    sa.Column('show_r_multiple_only', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_public_trade_shares_slug')
    )
    op.create_index(op.f('ix_public_trade_shares_trade_id'), 'public_trade_shares', ['trade_id'], unique=False)
    op.create_index('ix_public_trade_shares_user', 'public_trade_shares', ['user_id'], unique=False)
    op.create_index(op.f('ix_public_trade_shares_user_id'), 'public_trade_shares', ['user_id'], unique=False)
    op.create_table('rule_breaches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('trade_id', sa.String(length=36), nullable=True),
    sa.Column('breached_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['trading_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_breaches_account_id'), 'rule_breaches', ['account_id'], unique=False)
    op.create_index(op.f('ix_rule_breaches_rule_id'), 'rule_breaches', ['rule_id'], unique=False)
    op.create_index(op.f('ix_rule_breaches_trade_id'), 'rule_breaches', ['trade_id'], unique=False)
    op.create_index(op.f('ix_rule_breaches_user_id'), 'rule_breaches', ['user_id'], unique=False)
    op.create_index('ix_rule_breaches_user_time', 'rule_breaches', ['user_id', 'breached_at'], unique=False)
    op.create_table('trade_metrics',
    sa.Column('trade_id', sa.String(length=36), nullable=False),
    sa.Column('average_entry', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('average_exit', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('total_quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('pnl_percent', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('r_multiple', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('holding_period_seconds', sa.Integer(), nullable=True),
    sa.Column('max_adverse_excursion', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('max_favorable_excursion', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('journal_entry_id', sa.String(length=36), nullable=True),
    sa.Column('trade_id', sa.String(length=36), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('annotation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_journal_entry_id'), 'attachments', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_attachments_trade_id'), 'attachments', ['trade_id'], unique=False)
    op.create_table('mentor_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mentor_access_id', sa.String(length=36), nullable=False),
    sa.Column('student_user_id', sa.String(length=36), nullable=False),
    sa.Column('trade_id', sa.String(length=36), nullable=True),
    sa.Column('journal_entry_id', sa.String(length=36), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mentor_access_id'], ['mentor_access.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_comments_journal_entry_id'), 'mentor_comments', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_mentor_comments_mentor_access_id'), 'mentor_comments', ['mentor_access_id'], unique=False)
    op.create_index(op.f('ix_mentor_comments_student_user_id'), 'mentor_comments', ['student_user_id'], unique=False)
    op.create_index('ix_mentor_comments_trade', 'mentor_comments', ['trade_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_mentor_comments_trade_id'), 'mentor_comments', ['trade_id'], unique=False)
    op.create_foreign_key(
        "trades_journal_entry_id_fkey", "trades", "journal_entries", ["journal_entry_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("trades_journal_entry_id_fkey", "trades", type_="foreignkey")
    op.drop_index(op.f('ix_mentor_comments_trade_id'), table_name='mentor_comments')
    op.drop_index('ix_mentor_comments_trade', table_name='mentor_comments')
    op.drop_index(op.f('ix_mentor_comments_student_user_id'), table_name='mentor_comments')
    op.drop_index(op.f('ix_mentor_comments_mentor_access_id'), table_name='mentor_comments')
    op.drop_index(op.f('ix_mentor_comments_journal_entry_id'), table_name='mentor_comments')
    op.drop_table('mentor_comments')
    op.drop_index(op.f('ix_attachments_trade_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_journal_entry_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_table('trade_metrics')
    op.drop_index('ix_rule_breaches_user_time', table_name='rule_breaches')
    op.drop_index(op.f('ix_rule_breaches_user_id'), table_name='rule_breaches')
    op.drop_index(op.f('ix_rule_breaches_trade_id'), table_name='rule_breaches')
    op.drop_index(op.f('ix_rule_breaches_rule_id'), table_name='rule_breaches')
    op.drop_index(op.f('ix_rule_breaches_account_id'), table_name='rule_breaches')
    op.drop_table('rule_breaches')
    op.drop_index(op.f('ix_public_trade_shares_user_id'), table_name='public_trade_shares')
    op.drop_index('ix_public_trade_shares_user', table_name='public_trade_shares')
    op.drop_index(op.f('ix_public_trade_shares_trade_id'), table_name='public_trade_shares')
    op.drop_table('public_trade_shares')
    op.drop_index('ix_journal_user_date', table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_trade_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index('ix_executions_trade_time', table_name='executions')
    op.drop_index(op.f('ix_executions_trade_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_broker_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_trading_rules_user_id'), table_name='trading_rules')
    op.drop_index(op.f('ix_trading_rules_account_id'), table_name='trading_rules')
    op.drop_table('trading_rules')
    op.drop_index('ix_trades_user_status_opened', table_name='trades')
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_setup_tag'), table_name='trades')
    op.drop_index(op.f('ix_trades_instrument_id'), table_name='trades')
    op.drop_index('ix_trades_account_opened', table_name='trades')
    op.drop_index(op.f('ix_trades_account_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_daily_stats_date'), table_name='daily_stats')
    op.drop_index(op.f('ix_daily_stats_account_id'), table_name='daily_stats')
    op.drop_table('daily_stats')
    op.drop_index(op.f('ix_broker_syncs_account_id'), table_name='broker_syncs')
    op.drop_table('broker_syncs')
    op.drop_index(op.f('ix_billing_invoices_user_id'), table_name='billing_invoices')
    op.drop_index('ix_billing_invoices_user_created', table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_subscription_id'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_provider_invoice_id'), table_name='billing_invoices')
    op.drop_table('billing_invoices')
    op.drop_index(op.f('ix_ai_insights_user_id'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_account_id'), table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_index(op.f('ix_account_snapshots_date'), table_name='account_snapshots')
    op.drop_index(op.f('ix_account_snapshots_account_id'), table_name='account_snapshots')
    op.drop_table('account_snapshots')
    op.drop_index(op.f('ix_mentor_access_student_user_id'), table_name='mentor_access')
    op.drop_index('ix_mentor_access_student', table_name='mentor_access')
    op.drop_index(op.f('ix_mentor_access_mentor_email'), table_name='mentor_access')
    op.drop_table('mentor_access')
    op.drop_index(op.f('ix_leaderboard_profiles_user_id'), table_name='leaderboard_profiles')
    op.drop_table('leaderboard_profiles')
    op.drop_index('ix_billing_subscriptions_user_status', table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_user_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_provider_subscription_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_provider_customer_id'), table_name='billing_subscriptions')
    op.drop_table('billing_subscriptions')
    op.drop_index('ix_auth_tokens_user_purpose', table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_user_id'), table_name='auth_tokens')
    op.drop_index('ix_auth_tokens_token_hash', table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_asset_class'), table_name='instruments')
    op.drop_table('instruments')
    sa.Enum(name="accounttype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="aiinsighttype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="assetclass").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="authtokenpurpose").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="billingstatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="brokersyncstatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="brokersynctype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="direction").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="executiontype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="invoicestatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="journaltype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="leaderboardmetric").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="marketcondition").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="mentoraccessstatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="plan").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="ruleaction").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="ruletype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="tradestatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
