"""Import batches: file, format, pending rows and summary; fills and trades link to their batch.

Revision ID: 0003_import_batches
Revises: 0002_web_sessions
Create Date: 2026-10-08
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0003_import_batches'
down_revision: str | None = '0002_web_sessions'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_syncs', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('broker_syncs', sa.Column('file_format', sa.String(length=40), nullable=True))
    op.add_column('broker_syncs', sa.Column('source_timezone', sa.String(length=64), nullable=True))
    op.add_column('broker_syncs', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('broker_syncs', sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('broker_syncs', sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('broker_syncs', sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('executions', sa.Column('import_batch_id', sa.String(length=36), nullable=True))
    op.add_column('executions', sa.Column('fingerprint', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_executions_fingerprint'), 'executions', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_executions_import_batch_id'), 'executions', ['import_batch_id'], unique=False)
    op.create_foreign_key('executions_import_batch_id_fkey', 'executions', 'broker_syncs', ['import_batch_id'], ['id'], ondelete='SET NULL')
    op.add_column('trades', sa.Column('import_batch_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_trades_import_batch_id'), 'trades', ['import_batch_id'], unique=False)
    op.create_foreign_key('trades_import_batch_id_fkey', 'trades', 'broker_syncs', ['import_batch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('trades_import_batch_id_fkey', 'trades', type_='foreignkey')
    op.drop_index(op.f('ix_trades_import_batch_id'), table_name='trades')
    op.drop_column('trades', 'import_batch_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('executions_import_batch_id_fkey', 'executions', type_='foreignkey')
    op.drop_index(op.f('ix_executions_import_batch_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_fingerprint'), table_name='executions')
    op.drop_column('executions', 'fingerprint')
    op.drop_column('executions', 'import_batch_id')
    op.drop_column('broker_syncs', 'undone_at')
    op.drop_column('broker_syncs', 'imported_at')
    op.drop_column('broker_syncs', 'summary')
    op.drop_column('broker_syncs', 'payload')
    op.drop_column('broker_syncs', 'source_timezone')
    op.drop_column('broker_syncs', 'file_format')
    op.drop_column('broker_syncs', 'file_name')
    # ### end Alembic commands ###
